name: estudocaso2
description: Sistema de Gestão de Funcionários - Estudo de Caso 2
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  